/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   test/api-headers-form-test.html
 */

/// <reference path="../../webcomponentsjs/webcomponents-loader.d.ts" />
/// <reference path="../../web-component-tester/browser.d.ts" />
/// <reference path="../api-headers-form.d.ts" />

