/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   src/ApiHeadersForm.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.
// tslint:disable:no-any describes the API as best we are able today

import {html, LitElement} from 'lit-element';

import {ValidatableMixin} from '@anypoint-web-components/validatable-mixin/validatable-mixin.js';

import {ApiFormMixin} from '@api-components/api-form-mixin/api-form-mixin.js';

export {ApiHeadersForm};

/**
 * HTTP headers form build from AMF json/ld model.
 */
declare class ApiHeadersForm extends
  ValidatableMixin(
  ApiFormMixin(
  LitElement)) {
  readonly styles: any;
  legacy: any;
  value: any;
  model: any;
  readOnly: any;
  onvalue: Function|null;
  onmodel: Function|null;
  constructor();
  firstUpdated(): void;
  render(): any;

  /**
   * Registers an event handler for given type
   *
   * @param eventType Event type (name)
   * @param value The handler to register
   */
  _registerCallback(eventType: String|null, value: Function|null): void;

  /**
   * Appends an empty header to the list.
   */
  add(): void;

  /**
   * Focuses on last form item.
   */
  focusLast(): void;
  _modelChanged(model: any, readOnly: any): void;

  /**
   * Updates value of the element when model change.
   *
   * @param validate When true then it performs validation after setting
   * the value.
   */
  _updateValue(validate: Boolean|null): void;

  /**
   * Adds documentation for headers that doesn't have it already.
   *
   * @param model View model
   */
  _autoDescribeModel(model: Array<ModelItem|null>|null): void;

  /**
   * Queries for header information and updates header info if needed.
   *
   * @param item View model item
   * @param index Position of the item in `model` array
   */
  _fillModelDescription(item: ModelItem|null, index: Number|null): void;

  /**
   * Queries for a header definition.
   *
   * @param name header name to query
   * @returns Header definition or undefined.
   */
  _queryHeaderData(name: String|null): object|null|undefined;
  _getValidity(): any;
  _enableCheckedHandler(e: any): void;
  _nameChangeHandler(e: any): void;
  _valueChangeHandler(e: any): void;
  _optionalHanlder(e: any): void;
  _removeCustom(e: any): void;
}
